# practice with list
numbs = list(range(1, 20, 1))
print(numbs[2:6])
print(numbs[3:8])
print(numbs[0:1])
print(numbs[:7])
print(numbs[7:])
print(numbs[::2])
print(numbs[1:10:2])
print(numbs[-1:])
print(numbs[::-1])