#practice with string functions
print(", ".join(["qwerty", "qwerty"]))
print("hello me".replace("me","world"))
print("qwerty qwerty".startswith("qwerty"))
print("qwerty qwerty".endswith("qwerty"))
print("qwerty qwerty".upper())
print("QWERTY QWERTY".lower())
print("qwerty qwerty".split())
print(min(1,2,3,4,5,6,7,8,9,0))
print(max([1,2,3,4,5,6,7,8,9,0]))
print(abs(-88))
print(sum([1,2,3,4,5,6,7,8,9,0]))
